### ISSUE TITLE
You need to verify your Xiaomi account before beeing able to retreve valid information from servers

### ISSUE THREAD

**Issue by jiriks74** [Canny1913/miunlock#19]
I get this error after I put in the response code:

```python
Traceback (most recent call last):
File "/bulk/jirka/Downloads/miunlock-1.1/./main.py", line 23, in <module>
auth.login_tui("unlockApi")
File "/bulk/jirka/Downloads/miunlock-1.1/request.py", line 23, in login_tui
self.login(input("Go to account.xiaomi.com,log in and paste the code inside code.txt\n(dont forget to change the username and password or else it will fail)\nto devtools console (press f12 then select console) then copypaste the response to here: ".format(self.LOGIN_URL.format(sid)))) # please edit this,this is so bad
File "/bulk/jirka/Downloads/miunlock-1.1/request.py", line 38, in login
raise UserError(f"You need to verify your Xiaomi account before beeing able to retreve valid information from servers. Open this link to start verification process: \33[34m{data['notificationUrl']}\33[0m", 3)
request.UserError: [ERROR]: You need to verify your Xiaomi account before beeing able to retreve valid information from servers. Open this link to start verification process: https://account.xiaomi.com/identity/authStart?sid=passport&c…5TRcjyZ2nE57bgHihEWbCwTX1k0jqwVxS66k&_locale=en_US&_old=true
```

The link shows uncomplete...

**Comment by jiriks74** [comment]
Ok, figured it out.

**Comment by SpyrosMourelatos** [comment]
Then explain it for others that see the same error @jiriks74

**Comment by jiriks74** [comment]
It's not an error. It literally says what to do in [another issue](). You need to manually copy the link from the develper's console and edit it in the string you have to paste into the program, so it's the full link that doesn't have `...` in it. Then if you get this error, you open the link the program spits out, verify it, refresh the account website and get the output again and paste it into the program.
