### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by Antviau** [Canny1913/miunlock#2]
Hi, I'm using python 3.9 and have installed everything normally and yet I keep getting this

Traceback (most recent call last):
  File "C:\Users\Antoine Viau--Simoes\Downloads\miunlock-master\main.py", line 21, in <module>
    auth.login_tui("unlockApi")
  File "C:\Users\Antoine Viau--Simoes\Downloads\miunlock-master\request.py", line 24, in login_tui
    self.login(input("Go to account.xiaomi.com,log in and paste the code inside code.txt\n(dont forget to change the username and password or else it will fail)\nto devtools console (press f12 then select console) then copypaste the response to here: ".format(self.LOGIN_URL.format(sid)))) # please edit this,this is so bad
  File "C:\Users\Antoine Viau--Simoes\Downloads\miunlock-master\request.py", line 52, in login
    response.raise_for_status()
  File "C:\Users\Antoine Viau--Simoes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://unlock.update.miui.com/sts?d=wb_81043c1c-54ca-4677-9%E2%80%A6nonce=hv8A2eRgkTwBov2q&_ssign=okeSgKbt1N5oEXeuL7aduGro2mU%3D&clientSign=yKWE5Qj6oXd7iCymPTsVFvOi6xA%3D

**Comment by Canny1913** [comment]
The response isn't what it should be.

Try copy-pasting the code again, the response should look like this:
![image](https://user-images.githubusercontent.com/94744045/158867132-e0f43307-550b-4da9-a65a-b5abde8ca40f.png)

**Comment by Antviau** [comment]
Well, I tried doing so but it keeps giving me the same answer

**Comment by Antviau** [comment]
Figured it out, thanks
