### ISSUE TITLE
Where to response code?

### ISSUE THREAD

**Issue by Engmatic** [Canny1913/miunlock#7]
`Go to account.xiaomi.com,log in and paste the code inside code.txt
(dont forget to change the username and password or else it will fail)
to devtools console (press f12 then select console) then copypaste the response to here:`

i m using google chrome, i m login and pressing F12, selected console but i dont see any response code, please paste sample code.

**Comment by Canny1913** [comment]
copy and paste the code inside code.txt to console, change the "username" and "password" part then press enter. Copypaste the response to the tool then press enter.

Example code:

&&&START&&&{"qs":"(personal info)","ssecurity":"(personal info)","code":0,"passToken":"(personal info)","description":"成功","securityStatus":0,"nonce:"(personal info),"userId:"(personal info),"cUserId":"(personal info)","result":"ok","psecurity":"(personal info)","captchaUrl":null,"location":"(personal info)","pwd":1,"desc":"成功"}

**Comment by Attigliuzzo** [comment]
Hi @Canny1913 ,
i'm following your ONLY project to unlock the bootloader of Xiaomi phone. My Poco is under warranty so i'll unlock in the next future, not now.
Anyway i passed my account verify and a issue of shortned response, now your script gives me this, after i pasted my string and pressed enter:

`ERROR:root:Xiaomi server says shouldApply false, status 2
Press Ctrl-C to cancel, or enter to continue. `
`What is the SoC brand of the device you want to unlock? `mtk` for Mediatek, `qcom` for Qualcomm:`

Is it a critical error??  
The phone wasn't connected  to the PC while i was testing your script.

Thanks

**Comment by Canny1913** [comment]
that error is pretty normal, ignore it

**Comment by Attigliuzzo** [comment]
> that error is pretty normal, ignore it

Thanks, i found your shot from the original project:

![143931363-3f86cfcb-646e-4b77-affb-187268ff1e25](https://user-images.githubusercontent.com/42100711/181716802-ee2ec49d-ac8d-440e-b495-21979086f12f.png)

**Comment by madzul** [comment]
I got very-very long response. Every time i paste it, it got truncated
what should i do?
can you made the requests.py read it from file?

**Comment by Attigliuzzo** [comment]
> I got very-very long response. Every time i paste it, it got truncated what should i do? can you made the requests.py read it from file?

Make sure to select the White code or:

See [Here](https://github.com/Canny1913/miunlock/pull/8#issuecomment-1186278739) 

It Is for Firefox, It Is not available for Vivaldi but right click on the console and save as....

**Comment by unfairDude** [comment]
> > I got very-very long response. Every time i paste it, it got truncated what should i do? can you made the requests.py read it from file?
> 
> Make sure to select the whole code or:
> 
> See [Here](https://github.com/Canny1913/miunlock/pull/8#issuecomment-1186278739)
> 
> It Is for Firefox, It Is not available for Vivaldi but right click on the console and save as....

hi i pasted response code into terminal but i get error asking to verify my account

**Comment by Attigliuzzo** [comment]
> hi i pasted response code into terminal but i get error asking to verify my account

So validate your PC, the script will show you a link to authenticate your PC. I did in the past and now it doesn't show the request anymore.

**Comment by unfairDude** [comment]
Alright got it working

Il mar 9 ago 2022, 11:38 Attigliuzzo ***@***.***> ha scritto:

**Comment by unfairDude** [comment]
> > that error is pretty normal, ignore it
> 
> Thanks, i found your shot from the original project:
> 
> ![143931363-3f86cfcb-646e-4b77-affb-187268ff1e25](https://user-images.githubusercontent.com/42100711/181716802-ee2ec49d-ac8d-440e-b495-21979086f12f.png)

i did everything fine but after waiting the remaining 77hours its not printing token, but ask me to use official tool
please fix it i cant use any windows machine and vm emulation doesnt work for me

**Comment by Attigliuzzo** [comment]
I think the Xiaomi APIs have changed but i hope not, same problem there is with the XiaoMitoolV2.

**Comment by lvs1974** [comment]
Hi, has anybody managed to get an unlock code?

I got this:
`./main.py 
WARNING:root:No device detected in fastboot. Using manual mode.
Go to account.xiaomi.com,log in and paste the code inside code.txt
(dont forget to change the username and password or else it will fail)
to devtools console (press f12 then select console) then copypaste the response to here: &&&START&&&{"qs":"%3Fsid%3DunlockApi%26json%3Dfalse%26passive%3Dtrue%26hidden%3Dfalse%26_snsDefault%3Dfacebook%26_locale%3Den%26checkSafePhone%3Dtrue","ssecurity":"5KB8c9Ux/we+t9BW4kOV1Q==","code":0,"passToken":"V1:pwROAesIuzMBPe5slLSsQjE2WuIcv2rBpiZm4HWuKQWbkr4fY8ejo6Q11atMwjuIUspYAQO5jDdlgtF5XNYtIQeQ5FIfTz79CdE8hTGovwooa8U4oAfdzkW+fvy4x8QPztKfUHwDgu8i49GZngMGz+Bip5Syp3Jl+KXiB2k6QU2uCW0y6srRGc+LvDmB+JtaVhDbMe35GHuNOIFCF0oJ9Y4yWYesOsOO1PH0iLzlSxAgvbgXIrv1mWsXIBS3LhcI1HKqdMRE3Km5J0XQtG7Zk5M5z+BQ/dJXLknLXitbxr+JkoG2ml2AkcEJ9GgcTE6O","description":"成功","securityStatus":0,"nonce":1903445234995209216,"userId":8163055202,"cUserId":"2G4BUANZENEr2ta2Uon0ZVTQqzY","result":"ok","psecurity":"wei/VbD6oDXwP5SHu2V7ww==","captchaUrl":null,"location":"https://unlock.update.miui.com/sts?d=wb_772d23db-0fe3-4a71-9b8b-b54ca2afdef7&ticket=0&pwd=1&p_ts=1665255803000&fid=0&p_lm=1&auth=ME0txA%2Bo0kKYbKUH5GYF4dVj2n1WBTQ7A%2FqS2a0cRGExrA6AjvTfzlEIi5faVLeIugb85ctvmSVCOyfnGDTURgR2ugr%2BdAkDXawF9UntpDfMN6yoL77bjbYhrXrfY7DhB6FI2pd9rTwE2pdUHyXXX8nqBVIdUBk6GZfQaU4YE4A%3D&m=513&_group=DEFAULT&tsl=1&p_ca=0&p_ur=AT&p_idc=Europe&nonce=jahEr4hK%2BW0Bp38X&_ssign=i07I3hA2b1wBN1BZSka57Ic08Ls%3D","pwd":1,"child":0,"desc":"成功"}
ERROR:root:Xiaomi server says shouldApply false, status 2
Press Ctrl-C to cancel, or enter to continue. 
What is the SoC brand of the device you want to unlock? `mtk` for Mediatek, `qcom` for Qualcomm: qcom
Enter output from `fastboot getvar product` (Ctrl-C to cancel): sagit
Enter output from `fastboot getvar token` (Ctrl-C to cancel): fTYLOB9u3JFTLAnBqERW1FGMAWc
Xiaomi server says: An unlocked device is an easy target for malware which may damage your device or cause financial loss. It says that the unlock will wipe data.
Press Ctrl-C to cancel, or enter to continue. 
ERROR:root:invalid code != 0: {'code': 20045, 'description': '请使用官网普通用户解锁工具进行操作', 'descCN': '请使用官网普通用户解锁工具进行操作', 'descEN': 'Please use the common user tool on the official website.', 'uid': '8163055202'}
Traceback (most recent call last):
  File "/Users/serglvs1974/src/miunlock/./main.py", line 111, in <module>
    data = r.run()
  File "/Users/serglvs1974/src/miunlock/request.py", line 117, in run
    raise XiaomiError(STRINGS["en"].get(data.get("code", -1), STRINGS["en"][-1]).format(**data), data.get("code", 6))
request.XiaomiError: [ERROR]: Unknown error 20045
`

**Comment by JarrerLog** [comment]
> Hi, has anybody managed to get an unlock code?
> 
> I got this: `./main.py WARNING:root:No device detected in fastboot. Using manual mode. Go to account.xiaomi.com,log in and paste the code inside code.txt (dont forget to change the username and password or else it will fail) to devtools console (press f12 then select console) then copypaste the response to here: &&&START&&&{"qs":"%3Fsid%3DunlockApi%26json%3Dfalse%26passive%3Dtrue%26hidden%3Dfalse%26_snsDefault%3Dfacebook%26_locale%3Den%26checkSafePhone%3Dtrue","ssecurity":"5KB8c9Ux/we+t9BW4kOV1Q==","code":0,"passToken":"V1:pwROAesIuzMBPe5slLSsQjE2WuIcv2rBpiZm4HWuKQWbkr4fY8ejo6Q11atMwjuIUspYAQO5jDdlgtF5XNYtIQeQ5FIfTz79CdE8hTGovwooa8U4oAfdzkW+fvy4x8QPztKfUHwDgu8i49GZngMGz+Bip5Syp3Jl+KXiB2k6QU2uCW0y6srRGc+LvDmB+JtaVhDbMe35GHuNOIFCF0oJ9Y4yWYesOsOO1PH0iLzlSxAgvbgXIrv1mWsXIBS3LhcI1HKqdMRE3Km5J0XQtG7Zk5M5z+BQ/dJXLknLXitbxr+JkoG2ml2AkcEJ9GgcTE6O","description":"成功","securityStatus":0,"nonce":1903445234995209216,"userId":8163055202,"cUserId":"2G4BUANZENEr2ta2Uon0ZVTQqzY","result":"ok","psecurity":"wei/VbD6oDXwP5SHu2V7ww==","captchaUrl":null,"location":"https://unlock.update.miui.com/sts?d=wb_772d23db-0fe3-4a71-9b8b-b54ca2afdef7&ticket=0&pwd=1&p_ts=1665255803000&fid=0&p_lm=1&auth=ME0txA%2Bo0kKYbKUH5GYF4dVj2n1WBTQ7A%2FqS2a0cRGExrA6AjvTfzlEIi5faVLeIugb85ctvmSVCOyfnGDTURgR2ugr%2BdAkDXawF9UntpDfMN6yoL77bjbYhrXrfY7DhB6FI2pd9rTwE2pdUHyXXX8nqBVIdUBk6GZfQaU4YE4A%3D&m=513&_group=DEFAULT&tsl=1&p_ca=0&p_ur=AT&p_idc=Europe&nonce=jahEr4hK%2BW0Bp38X&_ssign=i07I3hA2b1wBN1BZSka57Ic08Ls%3D","pwd":1,"child":0,"desc":"成功"} ERROR:root:Xiaomi server says shouldApply false, status 2 Press Ctrl-C to cancel, or enter to continue. What is the SoC brand of the device you want to unlock? `mtk`for Mediatek,`qcom`for Qualcomm: qcom Enter output from`fastboot getvar product`(Ctrl-C to cancel): sagit Enter output from`fastboot getvar token`(Ctrl-C to cancel): fTYLOB9u3JFTLAnBqERW1FGMAWc Xiaomi server says: An unlocked device is an easy target for malware which may damage your device or cause financial loss. It says that the unlock will wipe data. Press Ctrl-C to cancel, or enter to continue. ERROR:root:invalid code != 0: {'code': 20045, 'description': '请使用官网普通用户解锁工具进行操作', 'descCN': '请使用官网普通用户解锁工具进行操作', 'descEN': 'Please use the common user tool on the official website.', 'uid': '8163055202'} Traceback (most recent call last): File "/miunlock/./main.py", line 111, in <module> data = r.run() File "request.py", line 117, in run raise XiaomiError(STRINGS["en"].get(data.get("code", -1), STRINGS["en"][-1]).format(**data), data.get("code", 6)) request.XiaomiError: [ERROR]: Unknown error 20045`

You can create a new Mi account and add it to the device to get the unlock right, the version has to wait 7 days to unlock, I have received the encrypted data and unlocked it successfully
